#!/bin/bash
# Environment Switcher for Tweight Development
# Usage: ./env.sh dev   or   ./env.sh prod
#
# What this does:
# 1. Loads config from config/{env}.env
# 2. Generates core/.env for Docker
# 3. Generates tweight/lib/config/environment.dart for Flutter
# 4. Sets environment for current shell session
#
# Never touch .env files manually again!

set -e

ENV_NAME=$1

if [ -z "$ENV_NAME" ]; then
    echo "❌ Usage: ./env.sh <environment>"
    echo ""
    echo "Available environments:"
    echo "  dev   - Local development (localhost:8000)"
    echo "  prod  - Production (api.chrisbuilds64.com)"
    echo ""
    echo "Example:"
    echo "  ./env.sh dev"
    exit 1
fi

CONFIG_FILE="config/${ENV_NAME}.env"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Config file not found: $CONFIG_FILE"
    echo ""
    echo "Available configs:"
    ls -1 config/*.env 2>/dev/null || echo "  (none)"
    exit 1
fi

echo "🔧 Switching to environment: $ENV_NAME"
echo ""

# Load config file
source "$CONFIG_FILE"

# 1. Generate core/.env for Docker
echo "📝 Generating core/.env for Docker..."
cat > core/.env << EOF
# Auto-generated by env.sh from $CONFIG_FILE
# DO NOT EDIT MANUALLY - use ./env.sh to switch environments

ENV=$ENV
CLERK_SECRET_KEY=$CLERK_SECRET_KEY
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
EOF

echo "✅ core/.env updated"

# 2. Generate tweight/lib/config/environment.dart for Flutter
echo "📝 Generating tweight/lib/config/environment.dart for Flutter..."
mkdir -p tweight/lib/config
cat > tweight/lib/config/environment.dart << EOF
// Auto-generated by env.sh from $CONFIG_FILE
// DO NOT EDIT MANUALLY - use ./env.sh to switch environments

class Environment {
  /// Current environment (development or production)
  static const String env = '$FLUTTER_ENV';

  /// Backend API base URL
  static const String baseUrl = '$API_URL';

  /// Is development mode
  static const bool isDevelopment = env == 'development';

  /// Is production mode
  static const bool isProduction = env == 'production';
}
EOF

echo "✅ tweight/lib/config/environment.dart updated"

# 3. Export for current shell session
export ENV="$ENV"
export BACKEND_URL="$BACKEND_URL"
export FLUTTER_ENV="$FLUTTER_ENV"
export API_URL="$API_URL"

echo ""
echo "✅ Environment switched to: $ENV_NAME"
echo ""
echo "📋 Active settings:"
echo "  Backend ENV:  $ENV"
echo "  Backend URL:  $BACKEND_URL"
echo "  Flutter ENV:  $FLUTTER_ENV"
echo "  Flutter URL:  $API_URL"
echo ""
echo "🚀 Next steps:"
if [ "$ENV_NAME" = "dev" ]; then
    echo "  1. Start backend:  cd core && docker-compose up -d"
    echo "  2. Run Flutter:    cd tweight && flutter run"
else
    echo "  1. Deploy backend: cd core && ./deploy.sh"
    echo "  2. Build Flutter:  cd tweight && flutter build ios --release"
fi
echo ""
